=== koczkatamas/kaitai_sandbox/KaitaiSandbox/KaitaiSandbox/ksy-json-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "JSON Schema for .ksy.json files",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "meta": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": { "type": "string", "pattern" : "^[a-z][a-z0-9_]*$" },
        "endian": { "enum": [ "le", "be" ] },
        "application": { "type": "string" },
        "file-extension": { "type": "string" }
      }
    },
    "seq": { "$ref": "#/definitions/AttrsSpec" },
    "types": { "$ref": "#/definitions/TypesSpec" },
    "enums": { "$ref": "#/definitions/EnumsSpec" },
    "instances": { "$ref": "#/definitions/InstancesSpec" }
  },
  "definitions": {
    "TypeSpec": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "seq": { "$ref": "#/definitions/AttrsSpec" },
        "types": { "$ref": "#/definitions/TypesSpec" },
        "enums": { "$ref": "#/definitions/EnumsSpec" },
        "instances": { "$ref": "#/definitions/InstancesSpec" }
      }
    },
    "TypesSpec": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": { "^([a-z0-9_])+$": { "$ref": "#/definitions/TypeSpec" } }
    },
    "AttrSpec": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": { "type": "string", "pattern" : "^[a-z][a-z0-9_]*$" },
        "type": {
          "anyOf": [
            { "type": "string" },
            {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "switch-on": { "type": "string", "pattern" : "^[a-z_][a-z0-9_.]*$" },
                "cases": {
                  "type": "object",
                  "additionalProperties": false,
                  "patternProperties": {
                    "^([A-Za-z0-9_\":])+$": { "type" : "string", "pattern" : "^[a-z_][a-z0-9_.]*$" }
                  }
                }
              }
            }
          ]
        },
        "repeat": { "enum": [ "eos", "expr", "until" ] },
        "repeat-until": { "type": "string" },
        "repeat-expr": { "$ref": "#/definitions/StringOrInteger" },
        "if": { "type": "string" },
        "doc": { "type": "string" },
        "enum": { "type": "string", "pattern" : "^[a-z][a-z0-9_]*$" },
        "encoding": { "enum": [ "ASCII", "UTF-8", "iso8859-1" ] },
        "process": { "type": "string", "pattern" : "^zlib|(xor|rol|ror)\\(.*\\)$"},
        "size": { "$ref": "#/definitions/StringOrInteger" },
        "size-eos": { "type": "boolean" },
        "contents": {
          "anyOf": [
            { "type": "string" },
            {
              "type": "array",
              "items": { "$ref": "#/definitions/StringOrInteger" }
            }
          ]
        }
      }
    },
    "AttrsSpec": {
      "type": "array",
      "items": { "$ref": "#/definitions/AttrSpec" }
    },
    "InstanceSpec": {
      "anyOf": [
        { "$ref": "#/definitions/AttrSpec" },
        {
          "properties": {
            "io": { "type": "string" },
            "pos": { "$ref": "#/definitions/StringOrInteger" },
            "size": { "$ref": "#/definitions/StringOrInteger" }
          }
        }
      ]
    },
    "InstancesSpec": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": { "^([a-z0-9_])+$": { "$ref": "#/definitions/InstanceSpec" } }
    },
    "EnumSpec": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": { "^([a-z0-9_])+$": { "type": "string" } }
    },
    "EnumsSpec": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": { "^([a-z0-9_])+$": { "$ref": "#/definitions/EnumSpec" } }
    },
    "StringOrInteger": {
      "anyOf": [
        { "type": "string" },
        { "type": "integer" }
      ]
    }
  }
}

=== koczkatamas/kaitai_sandbox/ksy-jsons/image/bmp.ksy.json
{
  "meta": {
    "id": "bmp",
    "file-extension": "bmp",
    "endian": "le"
  },
  "seq": [
    {
      "id": "file_header",
      "type": "file_header"
    },
    {
      "id": "dib_header",
      "type": "dib_header"
    }
  ],
  "types": {
    "file_header": {
      "seq": [
        {
          "id": "file_type",
          "size": 2
        },
        {
          "id": "file_size",
          "type": "u4"
        },
        {
          "id": "reserved1",
          "type": "u2"
        },
        {
          "id": "reserved2",
          "type": "u2"
        },
        {
          "id": "bitmap_ofs",
          "type": "s4"
        }
      ]
    },
    "dib_header": {
      "seq": [
        {
          "id": "dib_header_size",
          "type": "s4"
        },
        {
          "id": "bitmap_core_header",
          "type": "bitmap_core_header",
          "size": "dib_header_size - 4",
          "if": "dib_header_size == 12"
        },
        {
          "id": "bitmap_info_header",
          "type": "bitmap_info_header",
          "size": "dib_header_size - 4",
          "if": "dib_header_size == 40"
        },
        {
          "id": "bitmap_v5_header",
          "type": "bitmap_core_header",
          "size": "dib_header_size - 4",
          "if": "dib_header_size == 124"
        },
        {
          "id": "dib_header_body",
          "size": "dib_header_size - 4",
          "if": "dib_header_size != 12 and dib_header_size != 40 and dib_header_size != 124"
        }
      ]
    },
    "bitmap_core_header": {
      "seq": [
        {
          "id": "image_width",
          "type": "u2"
        },
        {
          "id": "image_height",
          "type": "u2"
        },
        {
          "id": "num_planes",
          "type": "u2"
        },
        {
          "id": "bits_per_pixel",
          "type": "u2"
        }
      ]
    },
    "bitmap_info_header": {
      "seq": [
        {
          "id": "image_width",
          "type": "u4"
        },
        {
          "id": "image_height",
          "type": "u4"
        },
        {
          "id": "num_planes",
          "type": "u2"
        },
        {
          "id": "bits_per_pixel",
          "type": "u2"
        },
        {
          "id": "compression",
          "type": "u4"
        },
        {
          "id": "size_image",
          "type": "u4"
        },
        {
          "id": "x_px_per_m",
          "type": "u4"
        },
        {
          "id": "y_px_per_m",
          "type": "u4"
        },
        {
          "id": "num_colors_used",
          "type": "u4"
        },
        {
          "id": "num_colors_important",
          "type": "u4"
        }
      ]
    }
  },
  "instances": {
    "image": {
      "pos": "file_header.bitmap_ofs",
      "size-eos": true
    }
  }
}

=== koczkatamas/kaitai_sandbox/ksy-jsons/game/doom_wad.ksy.json
{
  "meta": {
    "id": "doom_wad",
    "endian": "le",
    "application": "id Tech 1"
  },
  "seq": [
    {
      "id": "magic",
      "type": "str",
      "size": 4,
      "encoding": "ASCII"
    },
    {
      "id": "num_index_entries",
      "type": "s4",
      "doc": "Number of entries in the lump index"
    },
    {
      "id": "index_offset",
      "type": "s4",
      "doc": "Offset to the start of the index"
    }
  ],
  "types": {
    "index_entry": {
      "seq": [
        {
          "id": "offset",
          "type": "s4"
        },
        {
          "id": "size",
          "type": "s4"
        },
        {
          "id": "name",
          "type": "str",
          "size": 8,
          "encoding": "ASCII"
        }
      ],
      "instances": {
        "contents": {
          "io": "_root._io",
          "pos": "offset",
          "size": "size",
          "type": {
            "switch-on": "name",
            "cases": {
              "\"THINGS\\0\\0\"": "things",
              "\"LINEDEFS\"": "linedefs",
              "\"SIDEDEFS\"": "sidedefs",
              "\"VERTEXES\"": "vertexes",
              "\"BLOCKMAP\"": "blockmap",
              "\"SECTORS\\0\"": "sectors"
            }
          }
        }
      }
    },
    "things": {
      "seq": [
        {
          "id": "entries",
          "type": "thing",
          "repeat": "eos"
        }
      ]
    },
    "thing": {
      "seq": [
        {
          "id": "x",
          "type": "s2"
        },
        {
          "id": "y",
          "type": "s2"
        },
        {
          "id": "angle",
          "type": "u2"
        },
        {
          "id": "type",
          "type": "u2"
        },
        {
          "id": "flags",
          "type": "u2"
        }
      ]
    },
    "linedefs": {
      "seq": [
        {
          "id": "entries",
          "type": "linedef",
          "repeat": "eos"
        }
      ]
    },
    "linedef": {
      "seq": [
        {
          "id": "vertex_start_idx",
          "type": "u2"
        },
        {
          "id": "vertex_end_idx",
          "type": "u2"
        },
        {
          "id": "flags",
          "type": "u2"
        },
        {
          "id": "line_type",
          "type": "u2"
        },
        {
          "id": "sector_tag",
          "type": "u2"
        },
        {
          "id": "sidedef_right_idx",
          "type": "u2"
        },
        {
          "id": "sidedef_left_idx",
          "type": "u2"
        }
      ]
    },
    "sidedefs": {
      "seq": [
        {
          "id": "entries",
          "type": "sidedef",
          "repeat": "eos"
        }
      ]
    },
    "sidedef": {
      "seq": [
        {
          "id": "offset_x",
          "type": "s2"
        },
        {
          "id": "offset_y",
          "type": "s2"
        },
        {
          "id": "upper_texture_name",
          "type": "str",
          "size": 8,
          "encoding": "ASCII"
        },
        {
          "id": "lower_texture_name",
          "type": "str",
          "size": 8,
          "encoding": "ASCII"
        },
        {
          "id": "normal_texture_name",
          "type": "str",
          "size": 8,
          "encoding": "ASCII"
        },
        {
          "id": "sector_id",
          "type": "s2"
        }
      ]
    },
    "vertexes": {
      "seq": [
        {
          "id": "entries",
          "type": "vertex",
          "repeat": "eos"
        }
      ]
    },
    "vertex": {
      "seq": [
        {
          "id": "x",
          "type": "s2"
        },
        {
          "id": "y",
          "type": "s2"
        }
      ]
    },
    "blockmap": {
      "seq": [
        {
          "id": "origin_x",
          "type": "s2",
          "doc": "Grid origin, X coord"
        },
        {
          "id": "origin_y",
          "type": "s2",
          "doc": "Grid origin, Y coord"
        },
        {
          "id": "num_cols",
          "type": "s2",
          "doc": "Number of columns"
        },
        {
          "id": "num_rows",
          "type": "s2",
          "doc": "Number of rows"
        },
        {
          "id": "linedefs_in_block",
          "type": "blocklist",
          "repeat": "expr",
          "repeat-expr": "num_cols * num_rows",
          "doc": "Lists of linedefs for every block"
        }
      ],
      "types": {
        "blocklist": {
          "seq": [
            {
              "id": "offset",
              "type": "u2",
              "doc": "Offset to the list of linedefs"
            }
          ],
          "instances": {
            "linedefs": {
              "pos": "offset * 2",
              "type": "s2",
              "repeat": "until",
              "repeat-until": "_ == -1",
              "doc": "List of linedefs found in this block"
            }
          }
        }
      }
    },
    "sectors": {
      "seq": [
        {
          "id": "entries",
          "type": "sector",
          "repeat": "eos"
        }
      ]
    },
    "sector": {
      "seq": [
        {
          "id": "floor_z",
          "type": "s2"
        },
        {
          "id": "ceil_z",
          "type": "s2"
        },
        {
          "id": "floor_flat",
          "type": "str",
          "size": 8,
          "encoding": "ASCII"
        },
        {
          "id": "ceil_flat",
          "type": "str",
          "size": 8,
          "encoding": "ASCII"
        },
        {
          "id": "light",
          "type": "s2",
          "doc": "Light level of the sector [0..255]. Original engine uses COLORMAP to render lighting, so only 32 actual levels are available (i.e. 0..7, 8..15, etc).\n"
        },
        {
          "id": "special_type",
          "type": "u2",
          "enum": "special_sector"
        },
        {
          "id": "tag",
          "type": "u2",
          "doc": "Tag number. When the linedef with the same tag number is activated, some effect will be triggered in this sector.\n"
        }
      ],
      "enums": {
        "special_sector": {
          "0": "normal",
          "1": "d_light_flicker",
          "2": "d_light_strobe_fast",
          "3": "d_light_strobe_slow",
          "4": "d_light_strobe_hurt",
          "5": "d_damage_hellslime",
          "7": "d_damage_nukage",
          "8": "d_light_glow",
          "9": "secret",
          "10": "d_sector_door_close_in_30",
          "11": "d_damage_end",
          "12": "d_light_strobe_slow_sync",
          "13": "d_light_strobe_fast_sync",
          "14": "d_sector_door_raise_in_5_mins",
          "15": "d_friction_low",
          "16": "d_damage_super_hellslime",
          "17": "d_light_fire_flicker",
          "18": "d_damage_lava_wimpy",
          "19": "d_damage_lava_hefty",
          "20": "d_scroll_east_lava_damage",
          "21": "light_phased",
          "22": "light_sequence_start",
          "23": "light_sequence_special1",
          "24": "light_sequence_special2"
        }
      }
    }
  },
  "instances": {
    "index": {
      "pos": "index_offset",
      "type": "index_entry",
      "repeat": "expr",
      "repeat-expr": "num_index_entries"
    }
  }
}

=== koczkatamas/kaitai_sandbox/ksy-jsons/image/wmf.ksy.json
{
  "meta": {
    "id": "wmf",
    "endian": "le"
  },
  "seq": [
    {
      "id": "special_header",
      "type": "special_header"
    },
    {
      "id": "header",
      "type": "header"
    },
    {
      "id": "records",
      "type": "record",
      "repeat": "until",
      "repeat-until": "_.function == func::eof"
    }
  ],
  "types": {
    "special_header": {
      "seq": [
        {
          "id": "magic",
          "contents": [
            215,
            205,
            198,
            154
          ]
        },
        {
          "id": "handle",
          "contents": [
            0,
            0
          ]
        },
        {
          "id": "left",
          "type": "s2"
        },
        {
          "id": "top",
          "type": "s2"
        },
        {
          "id": "right",
          "type": "s2"
        },
        {
          "id": "bottom",
          "type": "s2"
        },
        {
          "id": "inch",
          "type": "u2"
        },
        {
          "id": "reserved",
          "contents": [
            0,
            0,
            0,
            0
          ]
        },
        {
          "id": "checksum",
          "type": "u2"
        }
      ]
    },
    "header": {
      "seq": [
        {
          "id": "metafile_type",
          "type": "u2",
          "enum": "metafile_type"
        },
        {
          "id": "header_size",
          "type": "u2"
        },
        {
          "id": "version",
          "type": "u2"
        },
        {
          "id": "size",
          "type": "u4"
        },
        {
          "id": "number_of_objects",
          "type": "u2"
        },
        {
          "id": "max_record",
          "type": "u4"
        },
        {
          "id": "number_of_members",
          "type": "u2"
        }
      ],
      "enums": {
        "metafile_type": {
          "1": "memory_metafile",
          "2": "disk_metafile"
        }
      }
    },
    "record": {
      "seq": [
        {
          "id": "size",
          "type": "u4"
        },
        {
          "id": "function",
          "type": "u2",
          "enum": "func"
        },
        {
          "id": "params",
          "size": "(size - 3) * 2"
        }
      ]
    }
  },
  "enums": {
    "func": {
      "0": "eof",
      "53": "realizepalette",
      "55": "setpalentries",
      "258": "setbkmode",
      "259": "setmapmode",
      "260": "setrop2",
      "261": "setrelabs",
      "262": "setpolyfillmode",
      "263": "setstretchbltmode",
      "264": "settextcharextra",
      "295": "restoredc",
      "313": "resizepalette",
      "322": "dibcreatepatternbrush",
      "329": "setlayout",
      "513": "setbkcolor",
      "521": "settextcolor",
      "529": "offsetviewportorg",
      "531": "lineto",
      "532": "moveto",
      "544": "offsetcliprgn",
      "552": "fillregion",
      "561": "setmapperflags",
      "564": "selectpalette",
      "804": "polygon",
      "805": "polyline",
      "522": "settextjustification",
      "523": "setwindoworg",
      "524": "setwindowext",
      "525": "setviewportorg",
      "526": "setviewportext",
      "527": "offsetwindoworg",
      "1040": "scalewindowext",
      "1042": "scaleviewportext",
      "1045": "excludecliprect",
      "1046": "intersectcliprect",
      "1048": "ellipse",
      "1049": "floodfill",
      "1065": "frameregion",
      "1078": "animatepalette",
      "1313": "textout",
      "1336": "polypolygon",
      "1352": "extfloodfill",
      "1051": "rectangle",
      "1055": "setpixel",
      "1564": "roundrect",
      "1565": "patblt",
      "30": "savedc",
      "2074": "pie",
      "2851": "stretchblt",
      "1574": "escape",
      "298": "invertregion",
      "299": "paintregion",
      "300": "selectclipregion",
      "301": "selectobject",
      "302": "settextalign",
      "2071": "arc",
      "2096": "chord",
      "2338": "bitblt",
      "2610": "exttextout",
      "3379": "setdibtodev",
      "2368": "dibbitblt",
      "2881": "dibstretchblt",
      "3907": "stretchdib",
      "496": "deleteobject",
      "247": "createpalette",
      "505": "createpatternbrush",
      "762": "createpenindirect",
      "763": "createfontindirect",
      "764": "createbrushindirect",
      "1791": "createregion"
    }
  }
}

=== koczkatamas/kaitai_sandbox/ksy-jsons/serialization/asn1/asn1_der.ksy.json
{
  "meta": {
    "id": "asn1_der"
  },
  "seq": [
    {
      "id": "type_tag",
      "type": "u1",
      "enum": "type_tag"
    },
    {
      "id": "len",
      "type": "len_encoded"
    },
    {
      "id": "body",
      "size": "len.result",
      "type": {
        "switch-on": "type_tag",
        "cases": {
          "type_tag::sequence_10": "body_sequence",
          "type_tag::sequence_30": "body_sequence",
          "type_tag::set": "body_sequence",
          "type_tag::utf8string": "body_utf8string",
          "type_tag::printable_string": "body_printable_string"
        }
      }
    }
  ],
  "types": {
    "len_encoded": {
      "seq": [
        {
          "id": "b1",
          "type": "u1"
        },
        {
          "id": "int2",
          "type": "u2be",
          "if": "b1 == 0x82"
        }
      ],
      "instances": {
        "result": {
          "value": "(b1 & 0x80 == 0) ? b1 : int2"
        }
      }
    },
    "body_sequence": {
      "seq": [
        {
          "id": "entries",
          "type": "asn1_der",
          "repeat": "eos"
        }
      ]
    },
    "body_utf8string": {
      "seq": [
        {
          "id": "str",
          "type": "str",
          "size-eos": true,
          "encoding": "UTF-8"
        }
      ]
    },
    "body_printable_string": {
      "seq": [
        {
          "id": "str",
          "type": "str",
          "size-eos": true,
          "encoding": "ASCII"
        }
      ]
    }
  },
  "enums": {
    "type_tag": {
      "0": "end_of_content",
      "1": "boolean",
      "2": "integer",
      "3": "bit_string",
      "4": "octet_string",
      "5": "null_value",
      "6": "object_id",
      "7": "object_descriptor",
      "8": "external",
      "9": "real",
      "10": "enumerated",
      "11": "embedded_pdv",
      "12": "utf8string",
      "13": "relative_oid",
      "16": "sequence_10",
      "19": "printable_string",
      "22": "ia5string",
      "48": "sequence_30",
      "49": "set"
    }
  }
}
