=== koczkatamas/kaitai_sandbox/KaitaiSandbox/KaitaiSandbox/ksy-json-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "JSON Schema for .ksy.json files",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "meta": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": { "type": "string", "pattern" : "^[a-z][a-z0-9_]*$" },
        "endian": { "enum": [ "le", "be" ] },
        "application": { "type": "string" },
        "file-extension": { "type": "string" }
      }
    },
    "seq": { "$ref": "#/definitions/AttrsSpec" },
    "types": { "$ref": "#/definitions/TypesSpec" },
    "enums": { "$ref": "#/definitions/EnumsSpec" },
    "instances": { "$ref": "#/definitions/InstancesSpec" }
  },
  "definitions": {
    "TypeSpec": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "seq": { "$ref": "#/definitions/AttrsSpec" },
        "types": { "$ref": "#/definitions/TypesSpec" },
        "enums": { "$ref": "#/definitions/EnumsSpec" },
        "instances": { "$ref": "#/definitions/InstancesSpec" }
      }
    },
    "TypesSpec": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": { "^([a-z0-9_])+$": { "$ref": "#/definitions/TypeSpec" } }
    },
    "AttrSpec": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": { "type": "string", "pattern" : "^[a-z][a-z0-9_]*$" },
        "type": {
          "anyOf": [
            { "type": "string" },
            {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "switch-on": { "type": "string", "pattern" : "^[a-z_][a-z0-9_.]*$" },
                "cases": {
                  "type": "object",
                  "additionalProperties": false,
                  "patternProperties": {
                    "^([A-Za-z0-9_\":])+$": { "type" : "string", "pattern" : "^[a-z_][a-z0-9_.]*$" }
                  }
                }
              }
            }
          ]
        },
        "repeat": { "enum": [ "eos", "expr", "until" ] },
        "repeat-until": { "type": "string" },
        "repeat-expr": { "$ref": "#/definitions/StringOrInteger" },
        "if": { "type": "string" },
        "doc": { "type": "string" },
        "enum": { "type": "string", "pattern" : "^[a-z][a-z0-9_]*$" },
        "encoding": { "enum": [ "ASCII", "UTF-8", "iso8859-1" ] },
        "process": { "type": "string", "pattern" : "^zlib|(xor|rol|ror)\\(.*\\)$"},
        "size": { "$ref": "#/definitions/StringOrInteger" },
        "size-eos": { "type": "boolean" },
        "contents": {
          "anyOf": [
            { "type": "string" },
            {
              "type": "array",
              "items": { "$ref": "#/definitions/StringOrInteger" }
            }
          ]
        }
      }
    },
    "AttrsSpec": {
      "type": "array",
      "items": { "$ref": "#/definitions/AttrSpec" }
    },
    "InstanceSpec": {
      "anyOf": [
        { "$ref": "#/definitions/AttrSpec" },
        {
          "properties": {
            "io": { "type": "string" },
            "pos": { "$ref": "#/definitions/StringOrInteger" },
            "size": { "$ref": "#/definitions/StringOrInteger" }
          }
        }
      ]
    },
    "InstancesSpec": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": { "^([a-z0-9_])+$": { "$ref": "#/definitions/InstanceSpec" } }
    },
    "EnumSpec": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": { "^([a-z0-9_])+$": { "type": "string" } }
    },
    "EnumsSpec": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": { "^([a-z0-9_])+$": { "$ref": "#/definitions/EnumSpec" } }
    },
    "StringOrInteger": {
      "anyOf": [
        { "type": "string" },
        { "type": "integer" }
      ]
    }
  }
}

=== koczkatamas/kaitai_sandbox/ksy-jsons/executable/elf.ksy.json
{
  "meta": {
    "id": "elf",
    "endian": "le",
    "application": "Executable and Linkable Format (SVR4 ABI and up), many *nix systems"
  },
  "seq": [
    {
      "id": "file_header",
      "type": "file_header"
    }
  ],
  "types": {
    "file_header": {
      "seq": [
        {
          "id": "magic",
          "size": 4,
          "contents": [
            127,
            "ELF"
          ],
          "doc": "File identification, must be 0x7f + \"ELF\"."
        },
        {
          "id": "bits",
          "type": "u1",
          "enum": "bits",
          "doc": "File class: designates target machine word size (32 or 64 bits). The size of many integer fields in this format will depend on this setting.\n"
        },
        {
          "id": "endian",
          "type": "u1",
          "enum": "endian",
          "doc": "Endianness used for all integers."
        },
        {
          "id": "ei_version",
          "type": "u1",
          "doc": "ELF header version."
        },
        {
          "id": "abi",
          "type": "u1",
          "enum": "os_abi",
          "doc": "Specifies which OS- and ABI-related extensions will be used in this ELF file.\n"
        },
        {
          "id": "abi_version",
          "type": "u1",
          "doc": "Version of ABI targeted by this ELF file. Interpretation depends on `abi` attribute.\n"
        },
        {
          "id": "pad",
          "size": 7
        },
        {
          "id": "e_type",
          "type": "u2",
          "enum": "obj_type"
        },
        {
          "id": "machine",
          "type": "u2",
          "enum": "machine"
        },
        {
          "id": "e_version",
          "type": "u4"
        },
        {
          "id": "entry_point",
          "type": {
            "switch-on": "bits",
            "cases": {
              "bits::b32": "u4",
              "bits::b64": "u8"
            }
          }
        },
        {
          "id": "program_header_offset",
          "type": {
            "switch-on": "bits",
            "cases": {
              "bits::b32": "u4",
              "bits::b64": "u8"
            }
          }
        },
        {
          "id": "section_header_offset",
          "type": {
            "switch-on": "bits",
            "cases": {
              "bits::b32": "u4",
              "bits::b64": "u8"
            }
          }
        },
        {
          "id": "flags",
          "size": 4
        },
        {
          "id": "e_ehsize",
          "type": "u2"
        },
        {
          "id": "program_header_entry_size",
          "type": "u2"
        },
        {
          "id": "qty_program_header",
          "type": "u2"
        },
        {
          "id": "section_header_entry_size",
          "type": "u2"
        },
        {
          "id": "qty_section_header",
          "type": "u2"
        },
        {
          "id": "section_names_idx",
          "type": "u2"
        }
      ]
    },
    "program_header": {
      "seq": [
        {
          "id": "type",
          "type": "u4",
          "enum": "ph_type"
        },
        {
          "id": "flags64",
          "type": "u4",
          "if": "_root.file_header.bits == bits::b64"
        },
        {
          "id": "offset",
          "type": {
            "switch-on": "_root.file_header.bits",
            "cases": {
              "bits::b32": "u4",
              "bits::b64": "u8"
            }
          }
        },
        {
          "id": "vaddr",
          "type": {
            "switch-on": "_root.file_header.bits",
            "cases": {
              "bits::b32": "u4",
              "bits::b64": "u8"
            }
          }
        },
        {
          "id": "paddr",
          "type": {
            "switch-on": "_root.file_header.bits",
            "cases": {
              "bits::b32": "u4",
              "bits::b64": "u8"
            }
          }
        },
        {
          "id": "filesz",
          "type": {
            "switch-on": "_root.file_header.bits",
            "cases": {
              "bits::b32": "u4",
              "bits::b64": "u8"
            }
          }
        },
        {
          "id": "memsz",
          "type": {
            "switch-on": "_root.file_header.bits",
            "cases": {
              "bits::b32": "u4",
              "bits::b64": "u8"
            }
          }
        },
        {
          "id": "flags32",
          "type": "u4",
          "if": "_root.file_header.bits == bits::b32"
        },
        {
          "id": "align",
          "type": {
            "switch-on": "_root.file_header.bits",
            "cases": {
              "bits::b32": "u4",
              "bits::b64": "u8"
            }
          }
        }
      ]
    },
    "section_header": {
      "seq": [
        {
          "id": "name_offset",
          "type": "u4"
        },
        {
          "id": "type",
          "type": "u4",
          "enum": "sh_type"
        },
        {
          "id": "flags",
          "type": {
            "switch-on": "_root.file_header.bits",
            "cases": {
              "bits::b32": "u4",
              "bits::b64": "u8"
            }
          }
        },
        {
          "id": "addr",
          "type": {
            "switch-on": "_root.file_header.bits",
            "cases": {
              "bits::b32": "u4",
              "bits::b64": "u8"
            }
          }
        },
        {
          "id": "offset",
          "type": {
            "switch-on": "_root.file_header.bits",
            "cases": {
              "bits::b32": "u4",
              "bits::b64": "u8"
            }
          }
        },
        {
          "id": "size",
          "type": {
            "switch-on": "_root.file_header.bits",
            "cases": {
              "bits::b32": "u4",
              "bits::b64": "u8"
            }
          }
        },
        {
          "id": "linked_section_idx",
          "type": "u4"
        },
        {
          "id": "info",
          "size": 4
        },
        {
          "id": "align",
          "type": {
            "switch-on": "_root.file_header.bits",
            "cases": {
              "bits::b32": "u4",
              "bits::b64": "u8"
            }
          }
        },
        {
          "id": "entry_size",
          "type": {
            "switch-on": "_root.file_header.bits",
            "cases": {
              "bits::b32": "u4",
              "bits::b64": "u8"
            }
          }
        }
      ],
      "instances": {
        "body": {
          "io": "_root._io",
          "pos": "offset",
          "size": "size"
        },
        "name": {
          "io": "_root.strings._io",
          "pos": "name_offset",
          "type": "strz",
          "encoding": "ASCII"
        }
      }
    },
    "strings": {
      "seq": [
        {
          "id": "entries",
          "type": "strz",
          "repeat": "eos",
          "encoding": "ASCII"
        }
      ]
    }
  },
  "instances": {
    "program_headers": {
      "pos": "file_header.program_header_offset",
      "repeat": "expr",
      "repeat-expr": "file_header.qty_program_header",
      "size": "file_header.program_header_entry_size",
      "type": "program_header"
    },
    "section_headers": {
      "pos": "file_header.section_header_offset",
      "repeat": "expr",
      "repeat-expr": "file_header.qty_section_header",
      "size": "file_header.section_header_entry_size",
      "type": "section_header"
    },
    "strings": {
      "pos": "section_headers[file_header.section_names_idx].offset",
      "size": "section_headers[file_header.section_names_idx].size",
      "type": "strings"
    }
  },
  "enums": {
    "bits": {
      "1": "b32",
      "2": "b64"
    },
    "endian": {
      "1": "le",
      "2": "be"
    },
    "os_abi": {
      "0": "system_v",
      "1": "hp_ux",
      "2": "netbsd",
      "3": "gnu",
      "6": "solaris",
      "7": "aix",
      "8": "irix",
      "9": "freebsd",
      "10": "tru64",
      "11": "modesto",
      "12": "openbsd",
      "13": "openvms",
      "14": "nsk",
      "15": "aros",
      "16": "fenixos",
      "17": "cloudabi",
      "18": "openvos"
    },
    "obj_type": {
      "1": "relocatable",
      "2": "executable",
      "3": "shared",
      "4": "core"
    },
    "machine": {
      "0": "not_set",
      "2": "sparc",
      "3": "x86",
      "8": "mips",
      "20": "powerpc",
      "40": "arm",
      "42": "superh",
      "50": "ia_64",
      "62": "x86_64",
      "183": "aarch64"
    },
    "ph_type": {
      "0": "null_type",
      "1": "load",
      "2": "dynamic",
      "3": "interp",
      "4": "note",
      "5": "shlib",
      "6": "phdr",
      "7": "tls",
      "1879048191": "hios",
      "1685382480": "gnu_eh_frame",
      "1685382481": "gnu_stack"
    },
    "sh_type": {
      "0": "null_type",
      "1": "progbits",
      "2": "symtab",
      "3": "strtab",
      "4": "rela",
      "5": "hash",
      "6": "dynamic",
      "7": "note",
      "8": "nobits",
      "9": "rel",
      "10": "shlib",
      "11": "dynsym",
      "14": "init_array",
      "15": "fini_array",
      "16": "preinit_array",
      "17": "group",
      "18": "symtab_shndx",
      "1879048175": "sunw_capchain",
      "1879048176": "sunw_capinfo",
      "1879048177": "sunw_symsort",
      "1879048178": "sunw_tlssort",
      "1879048179": "sunw_ldynsym",
      "1879048180": "sunw_dof",
      "1879048181": "sunw_cap",
      "1879048182": "sunw_signature",
      "1879048183": "sunw_annotate",
      "1879048184": "sunw_debugstr",
      "1879048185": "sunw_debug",
      "1879048186": "sunw_move",
      "1879048187": "sunw_comdat",
      "1879048188": "sunw_syminfo",
      "1879048189": "sunw_verdef",
      "1879048190": "sunw_verneed",
      "1879048191": "sunw_versym",
      "1879048192": "sparc_gotdata",
      "1879048193": "amd64_unwind"
    }
  }
}

=== koczkatamas/kaitai_sandbox/ksy-jsons/image/psx_tim.ksy.json
{
  "meta": {
    "id": "psx_tim",
    "endian": "le",
    "file-extension": "tim",
    "application": "Sony PlayStation (PSX) typical image format"
  },
  "seq": [
    {
      "id": "magic",
      "contents": [
        16,
        0,
        0,
        0
      ]
    },
    {
      "id": "flags",
      "type": "u4",
      "doc": "Encodes bits-per-pixel and whether CLUT is present in a file or not"
    },
    {
      "id": "clut",
      "type": "bitmap",
      "if": "has_clut",
      "doc": "CLUT (Color LookUp Table), one or several palettes for indexed color image, represented as a"
    },
    {
      "id": "img",
      "type": "bitmap"
    }
  ],
  "types": {
    "bitmap": {
      "seq": [
        {
          "id": "len",
          "type": "u4"
        },
        {
          "id": "origin_x",
          "type": "u2"
        },
        {
          "id": "origin_y",
          "type": "u2"
        },
        {
          "id": "width",
          "type": "u2"
        },
        {
          "id": "height",
          "type": "u2"
        },
        {
          "id": "body",
          "size": "len - 12"
        }
      ]
    }
  },
  "instances": {
    "has_clut": {
      "value": "flags & 0b1000 != 0"
    },
    "bpp": {
      "value": "flags & 0b0011"
    }
  },
  "enums": {
    "bpp": {
      "0": "bpp_4",
      "1": "bpp_8",
      "2": "bpp_16",
      "3": "bpp_24"
    }
  }
}

=== koczkatamas/kaitai_sandbox/ksy-jsons/image/gif.ksy.json
{
  "meta": {
    "id": "gif",
    "file-extension": "gif",
    "endian": "le"
  },
  "seq": [
    {
      "id": "header",
      "type": "header"
    },
    {
      "id": "logical_screen_descriptor",
      "type": "logical_screen_descriptor"
    },
    {
      "id": "global_color_table",
      "type": "global_color_table",
      "if": "logical_screen_descriptor.has_color_table",
      "size": "logical_screen_descriptor.color_table_size * 3"
    },
    {
      "id": "blocks",
      "type": "block",
      "repeat": "eos"
    }
  ],
  "types": {
    "header": {
      "seq": [
        {
          "id": "magic",
          "contents": "GIF"
        },
        {
          "id": "version",
          "size": 3,
          "encoding": "ASCII"
        }
      ]
    },
    "logical_screen_descriptor": {
      "seq": [
        {
          "id": "screen_width",
          "type": "u2"
        },
        {
          "id": "screen_height",
          "type": "u2"
        },
        {
          "id": "flags",
          "type": "u1"
        },
        {
          "id": "bg_color_index",
          "type": "u1"
        },
        {
          "id": "pixel_aspect_ratio",
          "type": "u1"
        }
      ],
      "instances": {
        "has_color_table": {
          "value": "(flags & 0b10000000) != 0"
        },
        "color_table_size": {
          "value": "2 << (flags & 7)"
        }
      }
    },
    "global_color_table": {
      "seq": [
        {
          "id": "entries",
          "type": "color_table_entry",
          "repeat": "eos"
        }
      ]
    },
    "color_table_entry": {
      "seq": [
        {
          "id": "red",
          "type": "u1"
        },
        {
          "id": "green",
          "type": "u1"
        },
        {
          "id": "blue",
          "type": "u1"
        }
      ]
    },
    "block": {
      "seq": [
        {
          "id": "block_type",
          "type": "u1",
          "enum": "block_type"
        },
        {
          "id": "body",
          "type": {
            "switch-on": "block_type",
            "cases": {
              "block_type::extension": "extension",
              "block_type::local_image_descriptor": "local_image_descriptor"
            }
          }
        }
      ]
    },
    "local_image_descriptor": {
      "seq": [
        {
          "id": "left",
          "type": "u2"
        },
        {
          "id": "top",
          "type": "u2"
        },
        {
          "id": "width",
          "type": "u2"
        },
        {
          "id": "height",
          "type": "u2"
        },
        {
          "id": "flags",
          "type": "u1"
        },
        {
          "id": "image_data",
          "type": "image_data"
        }
      ],
      "instances": {
        "has_color_table": {
          "value": "(flags & 0b10000000) != 0"
        },
        "has_interlace": {
          "value": "(flags & 0b01000000) != 0"
        },
        "has_sorted_color_table": {
          "value": "(flags & 0b00100000) != 0"
        },
        "color_table_size": {
          "value": "2 << (flags & 7)"
        }
      }
    },
    "image_data": {
      "seq": [
        {
          "id": "lzw_min_code_size",
          "type": "u1"
        },
        {
          "id": "subblocks",
          "type": "subblocks"
        }
      ]
    },
    "extension": {
      "seq": [
        {
          "id": "label",
          "type": "u1",
          "enum": "extension_label"
        },
        {
          "id": "body",
          "type": {
            "switch-on": "label",
            "cases": {
              "extension_label::application": "ext_application",
              "extension_label::comment": "subblocks",
              "extension_label::graphic_control": "ext_graphic_control",
              "_": "subblocks"
            }
          }
        }
      ]
    },
    "ext_application": {
      "seq": [
        {
          "id": "application_id",
          "type": "subblock"
        },
        {
          "id": "subblocks",
          "type": "subblock",
          "repeat": "until",
          "repeat-until": "_.num_bytes == 0"
        }
      ]
    },
    "ext_graphic_control": {
      "seq": [
        {
          "id": "block_size",
          "contents": [
            4
          ]
        },
        {
          "id": "flags",
          "type": "u1"
        },
        {
          "id": "delay_time",
          "type": "u2"
        },
        {
          "id": "transparent_idx",
          "type": "u1"
        },
        {
          "id": "terminator",
          "contents": [
            0
          ]
        }
      ],
      "instances": {
        "transparent_color_flag": {
          "value": "(flags & 0b00000001) != 0"
        },
        "user_input_flag": {
          "value": "(flags & 0b00000010) != 0"
        }
      }
    },
    "subblocks": {
      "seq": [
        {
          "id": "entries",
          "type": "subblock",
          "repeat": "until",
          "repeat-until": "_.num_bytes == 0"
        }
      ]
    },
    "subblock": {
      "seq": [
        {
          "id": "num_bytes",
          "type": "u1"
        },
        {
          "id": "bytes",
          "size": "num_bytes"
        }
      ]
    }
  },
  "enums": {
    "block_type": {
      "33": "extension",
      "44": "local_image_descriptor",
      "59": "end_of_file"
    },
    "extension_label": {
      "249": "graphic_control",
      "254": "comment",
      "255": "application"
    }
  }
}
