=== koczkatamas/kaitai_sandbox/KaitaiSandbox/KaitaiSandbox/ksy-json-schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema",
  "title": "JSON Schema for .ksy.json files",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "meta": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": { "type": "string", "pattern" : "^[a-z][a-z0-9_]*$" },
        "endian": { "enum": [ "le", "be" ] },
        "application": { "type": "string" },
        "file-extension": { "type": "string" }
      }
    },
    "seq": { "$ref": "#/definitions/AttrsSpec" },
    "types": { "$ref": "#/definitions/TypesSpec" },
    "enums": { "$ref": "#/definitions/EnumsSpec" },
    "instances": { "$ref": "#/definitions/InstancesSpec" }
  },
  "definitions": {
    "TypeSpec": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "seq": { "$ref": "#/definitions/AttrsSpec" },
        "types": { "$ref": "#/definitions/TypesSpec" },
        "enums": { "$ref": "#/definitions/EnumsSpec" },
        "instances": { "$ref": "#/definitions/InstancesSpec" }
      }
    },
    "TypesSpec": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": { "^([a-z0-9_])+$": { "$ref": "#/definitions/TypeSpec" } }
    },
    "AttrSpec": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": { "type": "string", "pattern" : "^[a-z][a-z0-9_]*$" },
        "type": {
          "anyOf": [
            { "type": "string" },
            {
              "type": "object",
              "additionalProperties": false,
              "properties": {
                "switch-on": { "type": "string", "pattern" : "^[a-z_][a-z0-9_.]*$" },
                "cases": {
                  "type": "object",
                  "additionalProperties": false,
                  "patternProperties": {
                    "^([A-Za-z0-9_\":])+$": { "type" : "string", "pattern" : "^[a-z_][a-z0-9_.]*$" }
                  }
                }
              }
            }
          ]
        },
        "repeat": { "enum": [ "eos", "expr", "until" ] },
        "repeat-until": { "type": "string" },
        "repeat-expr": { "$ref": "#/definitions/StringOrInteger" },
        "if": { "type": "string" },
        "doc": { "type": "string" },
        "enum": { "type": "string", "pattern" : "^[a-z][a-z0-9_]*$" },
        "encoding": { "enum": [ "ASCII", "UTF-8", "iso8859-1" ] },
        "process": { "type": "string", "pattern" : "^zlib|(xor|rol|ror)\\(.*\\)$"},
        "size": { "$ref": "#/definitions/StringOrInteger" },
        "size-eos": { "type": "boolean" },
        "contents": {
          "anyOf": [
            { "type": "string" },
            {
              "type": "array",
              "items": { "$ref": "#/definitions/StringOrInteger" }
            }
          ]
        }
      }
    },
    "AttrsSpec": {
      "type": "array",
      "items": { "$ref": "#/definitions/AttrSpec" }
    },
    "InstanceSpec": {
      "anyOf": [
        { "$ref": "#/definitions/AttrSpec" },
        {
          "properties": {
            "io": { "type": "string" },
            "pos": { "$ref": "#/definitions/StringOrInteger" },
            "size": { "$ref": "#/definitions/StringOrInteger" }
          }
        }
      ]
    },
    "InstancesSpec": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": { "^([a-z0-9_])+$": { "$ref": "#/definitions/InstanceSpec" } }
    },
    "EnumSpec": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": { "^([a-z0-9_])+$": { "type": "string" } }
    },
    "EnumsSpec": {
      "type": "object",
      "additionalProperties": false,
      "patternProperties": { "^([a-z0-9_])+$": { "$ref": "#/definitions/EnumSpec" } }
    },
    "StringOrInteger": {
      "anyOf": [
        { "type": "string" },
        { "type": "integer" }
      ]
    }
  }
}

=== koczkatamas/kaitai_sandbox/ksy-jsons/game/quake_pak.ksy.json
{
  "meta": {
    "id": "quake_pak",
    "file-extension": "pak",
    "application": "Quake game engine",
    "endian": "le"
  },
  "seq": [
    {
      "id": "magic",
      "contents": "PACK"
    },
    {
      "id": "index_ofs",
      "type": "u4"
    },
    {
      "id": "index_size",
      "type": "u4"
    }
  ],
  "instances": {
    "index": {
      "pos": "index_ofs",
      "size": "index_size",
      "type": "index"
    }
  },
  "types": {
    "index": {
      "seq": [
        {
          "id": "entries",
          "type": "index_entry",
          "repeat": "eos"
        }
      ]
    },
    "index_entry": {
      "seq": [
        {
          "id": "name",
          "type": "str",
          "size": 56,
          "encoding": "UTF-8"
        },
        {
          "id": "ofs",
          "type": "u4"
        },
        {
          "id": "size",
          "type": "u4"
        }
      ],
      "instances": {
        "body": {
          "pos": "ofs",
          "size": "size",
          "io": "_root._io"
        }
      }
    }
  }
}

=== koczkatamas/kaitai_sandbox/ksy-jsons/archive/zip.ksy.json
{
  "meta": {
    "id": "zip",
    "file-extension": "zip",
    "endian": "le"
  },
  "seq": [
    {
      "id": "sections",
      "type": "pk_section",
      "repeat": "eos"
    }
  ],
  "types": {
    "pk_section": {
      "seq": [
        {
          "id": "magic",
          "contents": "PK"
        },
        {
          "id": "section_type",
          "type": "u2"
        },
        {
          "id": "body",
          "type": {
            "switch-on": "section_type",
            "cases": {
              "513": "central_dir_entry",
              "1027": "local_file",
              "1541": "end_of_central_dir"
            }
          }
        }
      ]
    },
    "local_file": {
      "seq": [
        {
          "id": "header",
          "type": "local_file_header"
        },
        {
          "id": "body",
          "size": "header.compressed_size"
        }
      ]
    },
    "local_file_header": {
      "seq": [
        {
          "id": "version",
          "type": "u2"
        },
        {
          "id": "flags",
          "type": "u2"
        },
        {
          "id": "compression",
          "type": "u2",
          "enum": "compression"
        },
        {
          "id": "file_mod_time",
          "type": "u2"
        },
        {
          "id": "file_mod_date",
          "type": "u2"
        },
        {
          "id": "crc32",
          "type": "u4"
        },
        {
          "id": "compressed_size",
          "type": "u4"
        },
        {
          "id": "uncompressed_size",
          "type": "u4"
        },
        {
          "id": "file_name_len",
          "type": "u2"
        },
        {
          "id": "extra_len",
          "type": "u2"
        },
        {
          "id": "file_name",
          "type": "str",
          "size": "file_name_len",
          "encoding": "UTF-8"
        },
        {
          "id": "extra",
          "size": "extra_len"
        }
      ]
    },
    "central_dir_entry": {
      "seq": [
        {
          "id": "version_made_by",
          "type": "u2"
        },
        {
          "id": "version_needed_to_extract",
          "type": "u2"
        },
        {
          "id": "flags",
          "type": "u2"
        },
        {
          "id": "compression_method",
          "type": "u2"
        },
        {
          "id": "last_mod_file_time",
          "type": "u2"
        },
        {
          "id": "last_mod_file_date",
          "type": "u2"
        },
        {
          "id": "crc32",
          "type": "u4"
        },
        {
          "id": "compressed_size",
          "type": "u4"
        },
        {
          "id": "uncompressed_size",
          "type": "u4"
        },
        {
          "id": "file_name_len",
          "type": "u2"
        },
        {
          "id": "extra_len",
          "type": "u2"
        },
        {
          "id": "comment_len",
          "type": "u2"
        },
        {
          "id": "disk_number_start",
          "type": "u2"
        },
        {
          "id": "int_file_attr",
          "type": "u2"
        },
        {
          "id": "ext_file_attr",
          "type": "u4"
        },
        {
          "id": "local_header_offset",
          "type": "s4"
        },
        {
          "id": "file_name",
          "type": "str",
          "size": "file_name_len",
          "encoding": "UTF-8"
        },
        {
          "id": "extra",
          "size": "extra_len"
        },
        {
          "id": "comment",
          "type": "str",
          "size": "comment_len",
          "encoding": "UTF-8"
        }
      ]
    },
    "end_of_central_dir": {
      "seq": [
        {
          "id": "disk_of_end_of_central_dir",
          "type": "u2"
        },
        {
          "id": "disk_of_central_dir",
          "type": "u2"
        },
        {
          "id": "qty_central_dir_entries_on_disk",
          "type": "u2"
        },
        {
          "id": "qty_central_dir_entries_total",
          "type": "u2"
        },
        {
          "id": "central_dir_size",
          "type": "u4"
        },
        {
          "id": "central_dir_offset",
          "type": "u4"
        },
        {
          "id": "comment_len",
          "type": "u2"
        },
        {
          "id": "comment",
          "type": "str",
          "size": "comment_len",
          "encoding": "UTF-8"
        }
      ]
    }
  },
  "enums": {
    "compression": {
      "0": "none",
      "1": "shrunk",
      "2": "reduced_1",
      "3": "reduced_2",
      "4": "reduced_3",
      "5": "reduced_4",
      "6": "imploded",
      "8": "deflated",
      "9": "enhanced_deflated",
      "10": "pkware_dcl_imploded",
      "12": "bzip2",
      "14": "lzma",
      "18": "ibm_terse",
      "19": "ibm_lz77_z",
      "98": "ppmd"
    }
  }
}

=== koczkatamas/kaitai_sandbox/ksy-jsons/image/png.ksy.json
{
  "meta": {
    "id": "png",
    "file-extension": "png",
    "endian": "be"
  },
  "seq": [
    {
      "id": "magic",
      "contents": [
        137,
        80,
        78,
        71,
        13,
        10,
        26,
        10
      ]
    },
    {
      "id": "ihdr_len",
      "contents": [
        0,
        0,
        0,
        13
      ]
    },
    {
      "id": "ihdr_type",
      "contents": "IHDR"
    },
    {
      "id": "ihdr",
      "type": "ihdr_chunk"
    },
    {
      "id": "ihdr_crc",
      "size": 4
    },
    {
      "id": "chunks",
      "type": "chunk",
      "repeat": "eos"
    }
  ],
  "types": {
    "chunk": {
      "seq": [
        {
          "id": "len",
          "type": "u4"
        },
        {
          "id": "type",
          "type": "str",
          "size": 4,
          "encoding": "UTF-8"
        },
        {
          "id": "body",
          "size": "len",
          "type": {
            "switch-on": "type",
            "cases": {
              "\"PLTE\"": "plte_chunk",
              "\"cHRM\"": "chrm_chunk",
              "\"gAMA\"": "gama_chunk",
              "\"sRGB\"": "srgb_chunk",
              "\"bKGD\"": "bkgd_chunk",
              "\"pHYs\"": "phys_chunk",
              "\"tIME\"": "time_chunk",
              "\"tEXt\"": "text_chunk"
            }
          }
        },
        {
          "id": "crc",
          "size": 4
        }
      ]
    },
    "ihdr_chunk": {
      "seq": [
        {
          "id": "width",
          "type": "u4"
        },
        {
          "id": "height",
          "type": "u4"
        },
        {
          "id": "bit_depth",
          "type": "u1"
        },
        {
          "id": "color_type",
          "type": "u1",
          "enum": "color_type"
        },
        {
          "id": "compression_method",
          "type": "u1"
        },
        {
          "id": "filter_method",
          "type": "u1"
        },
        {
          "id": "interlace_method",
          "type": "u1"
        }
      ]
    },
    "plte_chunk": {
      "seq": [
        {
          "id": "entries",
          "type": "rgb",
          "repeat": "eos"
        }
      ]
    },
    "rgb": {
      "seq": [
        {
          "id": "r",
          "type": "u1"
        },
        {
          "id": "g",
          "type": "u1"
        },
        {
          "id": "b",
          "type": "u1"
        }
      ]
    },
    "chrm_chunk": {
      "seq": [
        {
          "id": "white_point",
          "type": "point"
        },
        {
          "id": "red",
          "type": "point"
        },
        {
          "id": "green",
          "type": "point"
        },
        {
          "id": "blue",
          "type": "point"
        }
      ]
    },
    "point": {
      "seq": [
        {
          "id": "x_int",
          "type": "u4"
        },
        {
          "id": "y_int",
          "type": "u4"
        }
      ],
      "instances": {
        "x": {
          "value": "x_int / 100000.0"
        },
        "y": {
          "value": "y_int / 100000.0"
        }
      }
    },
    "gama_chunk": {
      "seq": [
        {
          "id": "gamma_int",
          "type": "u4"
        }
      ],
      "instances": {
        "gamma_ratio": {
          "value": "100000.0 / gamma_int"
        }
      }
    },
    "srgb_chunk": {
      "seq": [
        {
          "id": "render_intent",
          "type": "u1",
          "enum": "intent"
        }
      ],
      "enums": {
        "intent": {
          "0": "perceptual",
          "1": "relative_colorimetric",
          "2": "saturation",
          "3": "absolute_colorimetric"
        }
      }
    },
    "bkgd_chunk": {
      "seq": [
        {
          "id": "bkgd",
          "type": {
            "switch-on": "_root.ihdr.color_type",
            "cases": {
              "color_type::greyscale": "bkgd_greyscale",
              "color_type::greyscale_alpha": "bkgd_greyscale",
              "color_type::truecolor": "bkgd_truecolor",
              "color_type::truecolor_alpha": "bkgd_truecolor",
              "color_type::indexed": "bkgd_indexed"
            }
          }
        }
      ]
    },
    "bkgd_greyscale": {
      "seq": [
        {
          "id": "value",
          "type": "u2"
        }
      ]
    },
    "bkgd_truecolor": {
      "seq": [
        {
          "id": "red",
          "type": "u2"
        },
        {
          "id": "green",
          "type": "u2"
        },
        {
          "id": "blue",
          "type": "u2"
        }
      ]
    },
    "bkgd_indexed": {
      "seq": [
        {
          "id": "palette_index",
          "type": "u1"
        }
      ]
    },
    "phys_chunk": {
      "seq": [
        {
          "id": "pixels_per_unit_x",
          "type": "u4"
        },
        {
          "id": "pixels_per_unit_y",
          "type": "u4"
        },
        {
          "id": "unit",
          "type": "u1",
          "enum": "phys_unit"
        }
      ]
    },
    "time_chunk": {
      "seq": [
        {
          "id": "year",
          "type": "u2"
        },
        {
          "id": "month",
          "type": "u1"
        },
        {
          "id": "day",
          "type": "u1"
        },
        {
          "id": "hour",
          "type": "u1"
        },
        {
          "id": "minute",
          "type": "u1"
        },
        {
          "id": "second",
          "type": "u1"
        }
      ]
    },
    "text_chunk": {
      "seq": [
        {
          "id": "keyword",
          "type": "strz",
          "encoding": "iso8859-1"
        },
        {
          "id": "text",
          "type": "str",
          "size-eos": true,
          "encoding": "iso8859-1"
        }
      ]
    }
  },
  "enums": {
    "color_type": {
      "0": "greyscale",
      "2": "truecolor",
      "3": "indexed",
      "4": "greyscale_alpha",
      "6": "truecolor_alpha"
    },
    "phys_unit": {
      "0": "unknown",
      "1": "meter"
    }
  }
}

=== koczkatamas/kaitai_sandbox/ksy-jsons/image/jpeg.ksy.json
{
  "meta": {
    "id": "jpeg",
    "endian": "be"
  },
  "seq": [
    {
      "id": "segments",
      "type": "segment",
      "repeat": "eos"
    }
  ],
  "types": {
    "segment": {
      "seq": [
        {
          "id": "magic",
          "contents": [
            255
          ]
        },
        {
          "id": "marker",
          "type": "u1",
          "enum": "marker"
        },
        {
          "id": "length",
          "type": "u2",
          "if": "marker != marker::soi and marker != marker::eoi"
        },
        {
          "id": "data",
          "size": "length - 2",
          "if": "marker != marker::soi and marker != marker::eoi",
          "type": {
            "switch-on": "marker",
            "cases": {
              "marker::app0": "segment_app0",
              "marker::app1": "segment_app1",
              "marker::sof0": "segment_sof0",
              "marker::sos": "segment_sos"
            }
          }
        },
        {
          "id": "image_data",
          "size-eos": true,
          "if": "marker == marker::sos"
        }
      ],
      "enums": {
        "marker": {
          "1": "tem",
          "192": "sof0",
          "193": "sof1",
          "194": "sof2",
          "195": "sof3",
          "196": "dht",
          "197": "sof5",
          "198": "sof6",
          "199": "sof7",
          "216": "soi",
          "217": "eoi",
          "218": "sos",
          "219": "dqt",
          "220": "dnl",
          "221": "dri",
          "224": "app0",
          "225": "app1",
          "226": "app2",
          "254": "com"
        }
      }
    },
    "segment_app0": {
      "seq": [
        {
          "id": "magic",
          "type": "str",
          "encoding": "ASCII",
          "size": 5
        },
        {
          "id": "version_major",
          "type": "u1"
        },
        {
          "id": "version_minor",
          "type": "u1"
        },
        {
          "id": "density_units",
          "type": "u1",
          "enum": "density_unit"
        },
        {
          "id": "density_x",
          "type": "u2",
          "doc": "Horizontal pixel density. Must not be zero."
        },
        {
          "id": "density_y",
          "type": "u2",
          "doc": "Vertical pixel density. Must not be zero."
        },
        {
          "id": "thumbnail_x",
          "type": "u1",
          "doc": "Horizontal pixel count of the following embedded RGB thumbnail. May be zero."
        },
        {
          "id": "thumbnail_y",
          "type": "u1",
          "doc": "Vertical pixel count of the following embedded RGB thumbnail. May be zero."
        },
        {
          "id": "thumbnail",
          "size": "thumbnail_x * thumbnail_y * 3",
          "doc": "Uncompressed 24 bit RGB (8 bits per color channel) raster thumbnail data in the order R0, G0, B0, ... Rn, Gn, Bn"
        }
      ],
      "enums": {
        "density_unit": {
          "0": "no_units",
          "1": "pixels_per_inch",
          "2": "pixels_per_cm"
        }
      }
    },
    "segment_app1": {
      "seq": [
        {
          "id": "magic",
          "type": "strz",
          "encoding": "ASCII"
        },
        {
          "id": "body",
          "type": {
            "switch-on": "magic",
            "cases": {
              "\"Exif\"": "exif_in_jpeg"
            }
          }
        }
      ]
    },
    "segment_sof0": {
      "seq": [
        {
          "id": "bits_per_sample",
          "type": "u1"
        },
        {
          "id": "image_height",
          "type": "u2"
        },
        {
          "id": "image_width",
          "type": "u2"
        },
        {
          "id": "num_components",
          "type": "u1"
        },
        {
          "id": "components",
          "type": "component",
          "repeat": "expr",
          "repeat-expr": "num_components"
        }
      ],
      "types": {
        "component": {
          "seq": [
            {
              "id": "id",
              "type": "u1",
              "enum": "component_id",
              "doc": "Component selector"
            },
            {
              "id": "sampling_factors",
              "type": "u1"
            },
            {
              "id": "quantization_table_id",
              "type": "u1"
            }
          ],
          "instances": {
            "sampling_x": {
              "value": "(sampling_factors & 0xf0) >> 4"
            },
            "sampling_y": {
              "value": "sampling_factors & 0xf"
            }
          }
        }
      }
    },
    "segment_sos": {
      "seq": [
        {
          "id": "num_components",
          "type": "u1",
          "doc": "Number of components in scan"
        },
        {
          "id": "components",
          "type": "component",
          "repeat": "expr",
          "repeat-expr": "num_components",
          "doc": "Scan components specification"
        },
        {
          "id": "start_spectral_selection",
          "type": "u1",
          "doc": "Start of spectral selection or predictor selection"
        },
        {
          "id": "end_spectral",
          "type": "u1",
          "doc": "End of spectral selection"
        },
        {
          "id": "appr_bit_pos",
          "type": "u1",
          "doc": "Successive approximation bit position high + Successive approximation bit position low or point transform"
        }
      ],
      "types": {
        "component": {
          "seq": [
            {
              "id": "id",
              "type": "u1",
              "enum": "component_id",
              "doc": "Scan component selector"
            },
            {
              "id": "huffman_table",
              "type": "u1"
            }
          ]
        }
      }
    },
    "exif_in_jpeg": {
      "seq": [
        {
          "id": "extra_zero",
          "contents": [
            0
          ]
        },
        {
          "id": "data",
          "size-eos": true,
          "type": "exif"
        }
      ]
    }
  },
  "enums": {
    "component_id": {
      "1": "y",
      "2": "cb",
      "3": "cr",
      "4": "i",
      "5": "q"
    }
  }
}

=== koczkatamas/kaitai_sandbox/ksy-jsons/network/pcap.ksy.json
{
  "meta": {
    "id": "pcap",
    "file-extension": "pcapdump",
    "endian": "le"
  },
  "seq": [
    {
      "id": "header",
      "type": "header"
    },
    {
      "id": "packets",
      "type": "packet",
      "repeat": "eos"
    }
  ],
  "types": {
    "header": {
      "seq": [
        {
          "id": "magic_number",
          "contents": [
            212,
            195,
            178,
            161
          ]
        },
        {
          "id": "version_major",
          "type": "u2"
        },
        {
          "id": "version_minor",
          "type": "u2"
        },
        {
          "id": "thiszone",
          "type": "s4"
        },
        {
          "id": "sigfigs",
          "type": "u4"
        },
        {
          "id": "snaplen",
          "type": "u4"
        },
        {
          "id": "network",
          "type": "u4",
          "enum": "linktype"
        }
      ]
    },
    "packet": {
      "seq": [
        {
          "id": "ts_sec",
          "type": "u4"
        },
        {
          "id": "ts_usec",
          "type": "u4"
        },
        {
          "id": "incl_len",
          "type": "u4"
        },
        {
          "id": "orig_len",
          "type": "u4"
        },
        {
          "id": "body",
          "size": "incl_len",
          "if": "_root.header.network != linktype::ppi and _root.header.network != linktype::ethernet"
        },
        {
          "id": "ppi_body",
          "type": "packet_ppi",
          "size": "incl_len",
          "if": "_root.header.network == linktype::ppi"
        },
        {
          "id": "ethernet_body",
          "type": "ethernet_frame",
          "size": "incl_len",
          "if": "_root.header.network == linktype::ethernet"
        }
      ]
    },
    "packet_ppi": {
      "seq": [
        {
          "id": "header",
          "type": "packet_ppi_header"
        },
        {
          "id": "fields",
          "type": "packet_ppi_field",
          "repeat": "eos"
        }
      ]
    },
    "packet_ppi_header": {
      "seq": [
        {
          "id": "pph_version",
          "type": "u1"
        },
        {
          "id": "pph_flags",
          "type": "u1"
        },
        {
          "id": "pph_len",
          "type": "u2"
        },
        {
          "id": "pph_dlt",
          "type": "u4"
        }
      ]
    },
    "packet_ppi_field": {
      "seq": [
        {
          "id": "pfh_type",
          "type": "u2"
        },
        {
          "id": "pfh_datalen",
          "type": "u2"
        },
        {
          "id": "body",
          "size": "pfh_datalen"
        }
      ]
    },
    "radio_802_11_common_body": {
      "seq": [
        {
          "id": "tsf_timer",
          "type": "u8"
        },
        {
          "id": "flags",
          "type": "u2"
        },
        {
          "id": "rate",
          "type": "u2"
        },
        {
          "id": "channel_freq",
          "type": "u2"
        },
        {
          "id": "channel_flags",
          "type": "u2"
        },
        {
          "id": "fhss_hopset",
          "type": "u1"
        },
        {
          "id": "fhss_pattern",
          "type": "u1"
        },
        {
          "id": "dbm_antsignal",
          "type": "s1"
        },
        {
          "id": "dbm_antnoise",
          "type": "s1"
        }
      ]
    }
  },
  "enums": {
    "linktype": {
      "0": "null_linktype",
      "1": "ethernet",
      "3": "ax25",
      "6": "ieee802_5",
      "7": "arcnet_bsd",
      "8": "slip",
      "9": "ppp",
      "10": "fddi",
      "50": "ppp_hdlc",
      "51": "ppp_ether",
      "100": "atm_rfc1483",
      "101": "raw",
      "104": "c_hdlc",
      "105": "ieee802_11",
      "107": "frelay",
      "108": "loop",
      "113": "linux_sll",
      "114": "ltalk",
      "117": "pflog",
      "119": "ieee802_11_prism",
      "122": "ip_over_fc",
      "123": "sunatm",
      "127": "ieee802_11_radiotap",
      "129": "arcnet_linux",
      "138": "apple_ip_over_ieee1394",
      "139": "mtp2_with_phdr",
      "140": "mtp2",
      "141": "mtp3",
      "142": "sccp",
      "143": "docsis",
      "144": "linux_irda",
      "147": "user0",
      "148": "user1",
      "149": "user2",
      "150": "user3",
      "151": "user4",
      "152": "user5",
      "153": "user6",
      "154": "user7",
      "155": "user8",
      "156": "user9",
      "157": "user10",
      "158": "user11",
      "159": "user12",
      "160": "user13",
      "161": "user14",
      "162": "user15",
      "163": "ieee802_11_avs",
      "165": "bacnet_ms_tp",
      "166": "ppp_pppd",
      "169": "gprs_llc",
      "170": "gpf_t",
      "171": "gpf_f",
      "177": "linux_lapd",
      "187": "bluetooth_hci_h4",
      "189": "usb_linux",
      "192": "ppi",
      "195": "ieee802_15_4",
      "196": "sita",
      "197": "erf",
      "201": "bluetooth_hci_h4_with_phdr",
      "202": "ax25_kiss",
      "203": "lapd",
      "204": "ppp_with_dir",
      "205": "c_hdlc_with_dir",
      "206": "frelay_with_dir",
      "209": "ipmb_linux",
      "215": "ieee802_15_4_nonask_phy",
      "220": "usb_linux_mmapped",
      "224": "fc_2",
      "225": "fc_2_with_frame_delims",
      "226": "ipnet",
      "227": "can_socketcan",
      "228": "ipv4",
      "229": "ipv6",
      "230": "ieee802_15_4_nofcs",
      "231": "dbus",
      "235": "dvb_ci",
      "236": "mux27010",
      "237": "stanag_5066_d_pdu",
      "239": "nflog",
      "240": "netanalyzer",
      "241": "netanalyzer_transparent",
      "242": "ipoib",
      "243": "mpeg_2_ts",
      "244": "ng40",
      "245": "nfc_llcp",
      "247": "infiniband",
      "248": "sctp",
      "249": "usbpcap",
      "250": "rtac_serial",
      "251": "bluetooth_le_ll",
      "253": "netlink",
      "254": "bluetooth_linux_monitor",
      "255": "bluetooth_bredr_bb",
      "256": "bluetooth_le_ll_with_phdr",
      "257": "profibus_dl",
      "258": "pktap",
      "259": "epon",
      "260": "ipmi_hpm_2",
      "261": "zwave_r1_r2",
      "262": "zwave_r3",
      "263": "wattstopper_dlm",
      "264": "iso_14443"
    },
    "pfh_type": {
      "2": "radio_802_11_common",
      "3": "radio_802_11n_mac_ext",
      "4": "radio_802_11n_mac_phy_ext",
      "5": "spectrum_map",
      "6": "process_info",
      "7": "capture_info"
    }
  }
}
